# 文件路径: configs/dataset/flickr30k.yaml

defaults:
  - _self_

name: 'ucm'

image_dir: '/data/clc/data/UCM_captions/imgs'
annotations_path: '/data/clc/data/UCM_captions/dataset.json'

# Dataloader Parameters
batch_size: 128  #vitb32
# batch_size: 64 #vitb16
# batch_size: 32 #vitl14
num_workers: 8
pin_memory: True

evaluation:
  # General evaluation settings
  log_interval: 100
  eval_fold5: false
  save_results: false