"""
Modality-axis ablation: coupled modulation variants for BSI.

The independent variant (the proposed method) gives the visual and the textual
branch their own scale and shift vectors.  In the coupled variants both branches
*keep* their own vectors and one modality additionally receives a term generated
from the other, so a coupled variant is exactly the independent variant plus a
cross-modal term.  Adding that term is then the only difference between the two,
which is what makes the ablation controlled: a drop cannot be attributed to a
loss of per-modality capacity.

    a_vis = a_vis_own + g( a_txt )
    b_vis = b_vis_own + g'( b_txt )

`source='visual'` swaps the roles of the two branches.  The bridge comes in two
forms, selected by `rank`:

    rank <= 0   one dense linear map (MaPLe-style coupling), d_dst x d_src
    rank >= 1   LoRA-style factorisation U V with U in R^{d_dst x r} and
                V in R^{r x d_src}, scaled by alpha / r

The deviation form (the `- 1` next to the source scale) makes the added term
exactly zero while the free parameters sit at their initial values, so every
variant starts from the same function as the independent variant, whatever the
bridge parameters are.  Both bridge factors are initialised away from zero:
with one of them at zero its gradient would vanish identically and the bridge
would never leave the identity.

Both classes keep the calling convention of `AffineProjection`
(`forward(x, is_text=False, i=0)`), so the transformer block in
`src/clip_mail/model.py` needs no modification.
"""
import torch
import torch.nn as nn
import torch.nn.functional as F


class CoupledAffineProjection(nn.Module):
    """Independent modulation plus a cross-modal term from the other branch."""

    def __init__(self, visual_dim, text_dim, source='text', rank=1, alpha=None):
        super().__init__()
        assert source in ('text', 'visual'), source
        self.source = source

        # both branches keep their own scale and shift, as in the independent variant
        self.visual_a = nn.Parameter(torch.ones(visual_dim))
        self.visual_b = nn.Parameter(torch.zeros(visual_dim))
        self.text_a = nn.Parameter(torch.ones(text_dim))
        self.text_b = nn.Parameter(torch.zeros(text_dim))

        # bridge: source modality -> the other one
        d_src = text_dim if source == 'text' else visual_dim
        d_dst = visual_dim if source == 'text' else text_dim
        self.full = rank is None or rank <= 0

        if self.full:
            # MaPLe-style: one dense linear map per injection point
            self.scale = 1.0
            self.W_a = nn.Parameter(torch.randn(d_dst, d_src) / d_src ** 0.5)
            self.W_b = nn.Parameter(torch.randn(d_dst, d_src) / d_src ** 0.5)
        else:
            # LoRA-style: U V, with the usual alpha / rank scaling so that
            # different ranks have a comparable effective magnitude
            r = int(rank)
            self.rank = r
            self.scale = (alpha if alpha is not None else r) / r
            self.U_a = nn.Parameter(torch.randn(d_dst, r) / d_dst ** 0.5)
            self.V_a = nn.Parameter(torch.randn(r, d_src) / d_src ** 0.5)
            self.U_b = nn.Parameter(torch.randn(d_dst, r) / d_dst ** 0.5)
            self.V_b = nn.Parameter(torch.randn(r, d_src) / d_src ** 0.5)

    def _cross_term(self):
        """Term generated by the source modality (exactly zero at identity init)."""
        if self.source == 'text':
            src_a, src_b = self.text_a, self.text_b
        else:
            src_a, src_b = self.visual_a, self.visual_b

        if self.full:
            return (F.linear(src_a - 1.0, self.W_a),
                    F.linear(src_b, self.W_b))
        return (self.scale * (self.U_a @ (self.V_a @ (src_a - 1.0))),
                self.scale * (self.U_b @ (self.V_b @ src_b)))

    def forward(self, x, is_text=False, i=0):
        if is_text:
            a, b = self.text_a, self.text_b
        else:
            a, b = self.visual_a, self.visual_b
        # the destination branch is the one that is *not* the source
        if is_text == (self.source == 'visual'):
            c_a, c_b = self._cross_term()
            a, b = a + c_a, b + c_b
        return x * a.to(x.dtype) + b.to(x.dtype)


class SharedScalarProjection(nn.Module):
    """A single scale and a single shift per injection point, shared by both
    modalities.  This is the opposite extreme of the ablation: no per-modality
    freedom and no per-channel freedom, hence a much smaller parameter budget
    than the independent variant.  Report its parameter count in the table."""

    def __init__(self, visual_dim, text_dim, **kwargs):
        super().__init__()
        self.a = nn.Parameter(torch.ones(1))
        self.b = nn.Parameter(torch.zeros(1))

    def forward(self, x, is_text=False, i=0):
        return x * self.a.to(x.dtype) + self.b.to(x.dtype)
